return {
  arrows = {
    circleRight = " ",
    chevronRight = "",
  },
  close = " ",
  code = " ",
  database = " ",
  download = " ",
  github = " ",
  docker = "󰡨",
  files = {
    new = " ",
    find = "󰱼 ",
  },
  folders = {
    closed = "󰉋 ",
  },
  git = {
    branch = "",
    linesAdded = " ",
    linesChanged = " ",
    linesRemoved = " ",
  },
  half_life = "󰘧",
  history = " ",
  lsp = {
    Error = " ",
    Warn = " ",
    Hint = "󰠠 ",
    Info = " ",
    Off = " ",
  },
  target = "󰀘",
  lineLeft = "▏",
  note = "󱘓 ",
  boldLineLeft = "▎",
  extraBoldLineLeft = "▍",
  boldLineRight = "▐",
  projects = " ",
  search = " ",
  settings = " ",
  tab = "󰌒 ",
}
