return {
  "folke/tokyonight.nvim",
  priority = 100,
  config = function()
    vim.cmd([[colorscheme tokyonight]])

    local hl = vim.api.nvim_set_hl
    local c = require("bootstrap.colors")

    hl(0, "AlphaFooter", { fg = c.cyan })
    hl(0, "AlphaHeader", { fg = c.fuksia })
    hl(0, "BufferCurrentSign", { fg = c.fuksia })
    hl(0, "BufferLineIndicatorSelected", { fg = c.fuksia })
    hl(0, "ColorColumn", { bg = c.red_dark })
    hl(0, "CursorLineNr", { fg = c.yellow })
    hl(0, "FloatBorder", { fg = c.fuksia })
    hl(0, "GitSignsAdd", { fg = c.green })
    hl(0, "GitSignsChange", { fg = c.blue_light })
    hl(0, "GitSignsDelete", { fg = c.red })
    hl(0, "IndentBlanklineContextChar", { fg = c.grey })
    hl(0, "LineNr", { fg = c.grey })
    hl(0, "NonText", { fg = c.normal })
    hl(0, "Normal", { fg = c.normal })
    hl(0, "NormalFloat", { bg = c.purple_light })
    hl(0, "NvimTreeFolderIcon", { fg = c.fuksia })
    hl(0, "TabLineSel", { fg = c.pink, bg = c.fuksia })
    hl(0, "TagBarVisibilityPrivate", { fg = c.red })
    hl(0, "TagBarVisibilityProtected", { fg = c.blue_light })
    hl(0, "TagBarVisibilityPublic", { fg = c.green })
    hl(0, "TelescopeBorder", { fg = c.cyan })
    hl(0, "TelescopeNormal", { fg = "none" })
    hl(0, "TelescopeTitle", { fg = c.fuksia })
    hl(0, "WhichKeyFloat", { bg = "none" })
    hl(0, "WinSeparator", { fg = c.cyan })
    hl(0, "gitcommitOverflow", { fg = c.red })
    hl(0, "gitcommitSummary", { fg = c.white })

    hl(0, "@boolean", { fg = c.yellow })
    hl(0, "@constant", { fg = c.pink_dark })
    hl(0, "@constructor", { fg = c.cyan_light })
    hl(0, "@namespace", { fg = c.cyan_light, italic = true })
    hl(0, "@punctuation.bracket", { fg = c.blue_light })
    hl(0, "@type", { fg = c.cyan_native })
    hl(0, "@variable.builtin", { fg = c.pink_dark, italic = true })

    -- hl(0, "@boolean", { fg = c.orange })
    -- 	hl(0,"@conditional", { fg = c.pink })
    -- hl(0,"@constant", { fg = c.cyan })
    -- hl(0,"@constructor", { fg = c.grey_light })
    -- 	hl(0,"@function", { fg = c.pink_dark })
    -- 	hl(0,"@include", { style = "italic", fg = c.pink })
    -- 	hl(0,"@keyword", { style = "italic", fg = c.grey })
    -- 	hl(0,"@keyword.function", { style = "italic", fg = c.purple })
    -- 	hl(0,"@keyword.return", { style = "italic", fg = c.pink })
    -- 	hl(0,"@method", { fg = c.grey_light })
    -- 	hl(0,"@parameter", { fg = c.cyan })
    -- 	hl(0,"@property", { fg = c.white })
    -- 	hl(0,"@punctuation.bracket", { fg = c.blue_light })
    -- hl(0,"@string", { fg = c.yellow })
    -- 	hl(0,"@tag", { fg = c.blue_light })
    -- 	hl(0,"@tag.attribute", { fg = c.pink })
    -- 	hl(0,"@tag.delimiter", { fg = c.grey })
    -- 	hl(0,"@type", { fg = c.normal })
    -- 	hl(0,"@type.builtin", { style = "italic", fg = c.orange })
    -- 	hl(0,"@variable", { fg = c.cyan_light })
    -- 	hl(0,"@variable.builtin", { style = "italic", fg = c.purple })
    -- 	hl(0,"@type.qualifier", { style = "italic", fg = c.grey })
  end,
}
